# Generated by Django 6.1.1 on 2026-09-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='+56 9', max_length=30, verbose_name='telefono'),
        ),
    ]
